// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :exec
INSERT INTO alerts (id, vehicle_id, type, description, timestamp, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAlertParams struct {
	ID          pgtype.UUID
	VehicleID   pgtype.UUID
	Type        string
	Description pgtype.Text
	Timestamp   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) error {
	_, err := q.db.Exec(ctx, createAlert,
		arg.ID,
		arg.VehicleID,
		arg.Type,
		arg.Description,
		arg.Timestamp,
		arg.CreatedAt,
	)
	return err
}

const getAlertsByVehicleAndTimeRange = `-- name: GetAlertsByVehicleAndTimeRange :many
SELECT id, vehicle_id, type, description, timestamp, created_at
FROM alerts
WHERE vehicle_id = $1 AND timestamp >= $2 AND timestamp <= $3
ORDER BY timestamp DESC
`

type GetAlertsByVehicleAndTimeRangeParams struct {
	VehicleID   pgtype.UUID
	Timestamp   pgtype.Timestamptz
	Timestamp_2 pgtype.Timestamptz
}

func (q *Queries) GetAlertsByVehicleAndTimeRange(ctx context.Context, arg GetAlertsByVehicleAndTimeRangeParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, getAlertsByVehicleAndTimeRange, arg.VehicleID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Type,
			&i.Description,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertsByVehicleID = `-- name: GetAlertsByVehicleID :many
SELECT id, vehicle_id, type, description, timestamp, created_at
FROM alerts
WHERE vehicle_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type GetAlertsByVehicleIDParams struct {
	VehicleID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) GetAlertsByVehicleID(ctx context.Context, arg GetAlertsByVehicleIDParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, getAlertsByVehicleID, arg.VehicleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Type,
			&i.Description,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAlerts = `-- name: GetAllAlerts :many
SELECT id, vehicle_id, type, description, timestamp, created_at
FROM alerts
ORDER BY timestamp DESC
LIMIT $1 OFFSET $2
`

type GetAllAlertsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllAlerts(ctx context.Context, arg GetAllAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, getAllAlerts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Type,
			&i.Description,
			&i.Timestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
