// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID          pgtype.UUID
	VehicleID   pgtype.UUID
	Type        string
	Description pgtype.Text
	Timestamp   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type TelemetryEvent struct {
	ID        pgtype.UUID
	VehicleID pgtype.UUID
	Timestamp pgtype.Timestamptz
	Latitude  pgtype.Numeric
	Longitude pgtype.Numeric
	Speed     pgtype.Numeric
	FuelLevel pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

type Vehicle struct {
	ID        pgtype.UUID
	Plate     string
	Model     string
	CreatedAt pgtype.Timestamptz
}
