// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemetry.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTelemetryEvent = `-- name: CreateTelemetryEvent :exec
INSERT INTO telemetry_events (id, vehicle_id, timestamp, latitude, longitude, speed, fuel_level, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateTelemetryEventParams struct {
	ID        pgtype.UUID
	VehicleID pgtype.UUID
	Timestamp pgtype.Timestamptz
	Latitude  pgtype.Numeric
	Longitude pgtype.Numeric
	Speed     pgtype.Numeric
	FuelLevel pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateTelemetryEvent(ctx context.Context, arg CreateTelemetryEventParams) error {
	_, err := q.db.Exec(ctx, createTelemetryEvent,
		arg.ID,
		arg.VehicleID,
		arg.Timestamp,
		arg.Latitude,
		arg.Longitude,
		arg.Speed,
		arg.FuelLevel,
		arg.CreatedAt,
	)
	return err
}

const getLastTelemetryEventByVehicleID = `-- name: GetLastTelemetryEventByVehicleID :one
SELECT id, vehicle_id, timestamp, latitude, longitude, speed, fuel_level, created_at
FROM telemetry_events
WHERE vehicle_id = $1
ORDER BY timestamp DESC
LIMIT 1
`

func (q *Queries) GetLastTelemetryEventByVehicleID(ctx context.Context, vehicleID pgtype.UUID) (TelemetryEvent, error) {
	row := q.db.QueryRow(ctx, getLastTelemetryEventByVehicleID, vehicleID)
	var i TelemetryEvent
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Timestamp,
		&i.Latitude,
		&i.Longitude,
		&i.Speed,
		&i.FuelLevel,
		&i.CreatedAt,
	)
	return i, err
}

const getTelemetryEventsByVehicleAndTimeRange = `-- name: GetTelemetryEventsByVehicleAndTimeRange :many
SELECT id, vehicle_id, timestamp, latitude, longitude, speed, fuel_level, created_at
FROM telemetry_events
WHERE vehicle_id = $1 AND timestamp >= $2 AND timestamp <= $3
ORDER BY timestamp DESC
`

type GetTelemetryEventsByVehicleAndTimeRangeParams struct {
	VehicleID   pgtype.UUID
	Timestamp   pgtype.Timestamptz
	Timestamp_2 pgtype.Timestamptz
}

func (q *Queries) GetTelemetryEventsByVehicleAndTimeRange(ctx context.Context, arg GetTelemetryEventsByVehicleAndTimeRangeParams) ([]TelemetryEvent, error) {
	rows, err := q.db.Query(ctx, getTelemetryEventsByVehicleAndTimeRange, arg.VehicleID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryEvent
	for rows.Next() {
		var i TelemetryEvent
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Timestamp,
			&i.Latitude,
			&i.Longitude,
			&i.Speed,
			&i.FuelLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryEventsByVehicleID = `-- name: GetTelemetryEventsByVehicleID :many
SELECT id, vehicle_id, timestamp, latitude, longitude, speed, fuel_level, created_at
FROM telemetry_events
WHERE vehicle_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type GetTelemetryEventsByVehicleIDParams struct {
	VehicleID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) GetTelemetryEventsByVehicleID(ctx context.Context, arg GetTelemetryEventsByVehicleIDParams) ([]TelemetryEvent, error) {
	rows, err := q.db.Query(ctx, getTelemetryEventsByVehicleID, arg.VehicleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryEvent
	for rows.Next() {
		var i TelemetryEvent
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Timestamp,
			&i.Latitude,
			&i.Longitude,
			&i.Speed,
			&i.FuelLevel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
