// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicle = `-- name: CreateVehicle :exec
INSERT INTO vehicles (id, plate, model, created_at) 
VALUES ($1, $2, $3, $4)
`

type CreateVehicleParams struct {
	ID        pgtype.UUID
	Plate     string
	Model     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) error {
	_, err := q.db.Exec(ctx, createVehicle,
		arg.ID,
		arg.Plate,
		arg.Model,
		arg.CreatedAt,
	)
	return err
}

const getAllVehicles = `-- name: GetAllVehicles :many
SELECT id, plate, model, created_at 
FROM vehicles 
ORDER BY created_at DESC
`

func (q *Queries) GetAllVehicles(ctx context.Context) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, getAllVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.Plate,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVehicleByID = `-- name: GetVehicleByID :one
SELECT id, plate, model, created_at 
FROM vehicles 
WHERE id = $1
`

func (q *Queries) GetVehicleByID(ctx context.Context, id pgtype.UUID) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByID, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}

const getVehicleByPlate = `-- name: GetVehicleByPlate :one
SELECT id, plate, model, created_at 
FROM vehicles 
WHERE plate = $1
`

func (q *Queries) GetVehicleByPlate(ctx context.Context, plate string) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByPlate, plate)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Plate,
		&i.Model,
		&i.CreatedAt,
	)
	return i, err
}
